export const CREATE_FOLDER_ACTION = "CREATE_FOLDER_ACTION";
export const CREATE_FOLDER_ACTION_FAIL = "CREATE_FOLDER_ACTION_FAIL";

export const GET_FOLDERS_ACTION = "GET_FOLDERS_ACTION";
export const GET_FOLDERS_ACTION_FAIL = "GET_FOLDERS_ACTION_FAIL";

export const GET_FILES_ACTION = "GET_FILES_ACTION";
export const GET_FILES_ACTION_FAIL = "GET_FILES_ACTION_FAIL";

export const SAVE_FILE_ACTION = "SAVE_FILE_ACTION";
export const SAVE_FILE_ACTION_FAIL = "SAVE_FILE_ACTION_FAIL";

export const UPLOAD_FILE_PROGRESS = "UPLOAD_FILE_PROGRESS";
export const UPLOAD_FILE_ACTION = "UPLOAD_FILE_ACTION";
export const UPLOAD_FILE_ACTION_FAIL = "UPLOAD_FILE_ACTION_FAIL";
